/* Copyright (C) 2018 Yosshin(@yosshin4004) */

#ifndef _CONFIG_H_
#define _CONFIG_H_

/* ピクセルフォーマット */
#define PIXEL_FORMAT_UNORM8_RGBA				0
#define PIXEL_FORMAT_FP16_RGBA					1
#define PIXEL_FORMAT_FP32_RGBA					2

/* テクスチャフィルタ */
#define TEXTURE_FILTER_NEAREST					0
#define TEXTURE_FILTER_LINEAR					1

/* テクスチャラップ */
#define TEXTURE_WRAP_REPEAT						0
#define TEXTURE_WRAP_CLAMP_TO_EDGE				1
#define TEXTURE_WRAP_MIRRORED_REPEAT			2

/* スワップインターバル */
#define SWAP_INTERVAL_ALLOW_TEARING				0
#define SWAP_INTERVAL_HSYNC						1
#define SWAP_INTERVAL_VSYNC						2

/* 引数 */
#define	SCREEN_WIDTH							ARG_SCREEN_WIDTH
#define	SCREEN_HEIGHT							ARG_SCREEN_HEIGHT
#define	NUM_SOUND_BUFFER_SAMPLES				ARG_NUM_SOUND_BUFFER_SAMPLES
#define	NUM_SOUND_BUFFER_AVAILABLE_SAMPLES		ARG_NUM_SOUND_BUFFER_AVAILABLE_SAMPLES
#define	NUM_SOUND_BUFFER_SAMPLES_PER_DISPATCH	ARG_NUM_SOUND_BUFFER_SAMPLES_PER_DISPATCH
#define	ENABLE_BACK_BUFFER						ARG_ENABLE_BACK_BUFFER
#define	ENABLE_FRAME_COUNT_UNIFORM				ARG_ENABLE_FRAME_COUNT_UNIFORM
#define	ENABLE_MIPMAP_GENERATION				ARG_ENABLE_MIPMAP_GENERATION
#define	NUM_MIPMAP_LEVELS						ARG_NUM_MIPMAP_LEVELS
#define	NUM_RENDER_TARGETS						ARG_NUM_RENDER_TARGETS
#define	PIXEL_FORMAT							ARG_PIXEL_FORMAT
#define	TEXTURE_FILTER							ARG_TEXTURE_FILTER
#define	TEXTURE_WRAP							ARG_TEXTURE_WRAP
#define	ENABLE_SWAP_INTERVAL_CONTROL			ARG_ENABLE_SWAP_INTERVAL_CONTROL
#define	SWAP_INTERVAL							ARG_SWAP_INTERVAL
#define	ENABLE_SOUND_DISPATCH_WAIT				ARG_ENABLE_SOUND_DISPATCH_WAIT
#define	USE_TINYHEADER							ARG_USE_TINYHEADER
#define	USE_TINYIMPORT							ARG_USE_TINYIMPORT


/* glTexImage2D の代わりに glExtTexStorage2D を使うか */
#define PREFER_GL_TEX_STORAGE_2D				1

/* サウンド出力デバイスの秒間サンプル数 */
#define NUM_SOUND_SAMPLES_PER_SEC				48000

/* サウンド出力デバイスのチャンネル数 */
#define NUM_SOUND_CHANNELS						2

/* サウンドのサンプルの型 */
#define SOUND_SAMPLE_TYPE						float


#endif
