name: release

on: push

jobs:
  build:
    name: Build release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # https://github.com/actions/checkout v6.0.3

      - name: Build Artifacts
        run: cmd.exe /c '.\scripts\make-artifacts.bat' ${{ github.ref_name }}

      - name: Archive Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # https://github.com/actions/upload-artifact v7.0.1
        with:
           name: "artifacts"
           path: artifacts

      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # https://github.com/softprops/action-gh-release v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.zip
